### ISSUE TITLE
Problem with topology.json and config.json Video 2 and 3

### ISSUE THREAD

**Issue by johnshearing** [carloslodelar/cardano-course#2]
Greetings. I am loving your course. Much thanks for the great content.
I had trouble with topology.json and config.json
Those files linked to in the documentation do not function.
This is explained and resolved on the [Cardano StackExchange](https://cardano.stackexchange.com/questions/11022/official-iog-cardano-node-course-video-3-node-wont-start/11024#11024)
So I imagine the files need to be changed and the documentation updated so that others student don't run into the same issue.
Much thanks for the course.

**Comment by carloslodelar** [comment]
Hey, thanks. Yeah it depends on the version of cardano you use. I'll make sure to update those topology files!

**Comment by carloslodelar** [comment]
I just tested these and they work just fine, 
```
wget https://book.world.dev.cardano.org/environments/preview/config.json
wget https://book.world.dev.cardano.org/environments/preview/topology.json
wget https://book.world.dev.cardano.org/environments/preview/byron-genesis.json
wget https://book.world.dev.cardano.org/environments/preview/shelley-genesis.json
wget https://book.world.dev.cardano.org/environments/preview/alonzo-genesis.json
```

topology file is a P2P topology file 

```
{
  "localRoots": [
    {
      "accessPoints": [],
      "advertise": false,
      "valency": 1
    }
  ],
  "publicRoots": [
    {
      "accessPoints": [
        {
          "address": "preview-node.world.dev.cardano.org",
          "port": 30002
        }
      ],
      "advertise": false
    }
  ],
  "useLedgerAfterSlot": 322000
}
```

and config file has '  "EnableP2P": true,' 

So not sure why you had  a non-p2p topology file. =(

**Comment by johnshearing** [comment]
Hi Carlos,
>So not sure why you had a non-p2p topology file. =(<

All the setup conditions were specified in the [Stackexchange post linked here](https://cardano.stackexchange.com/questions/11022/official-iog-cardano-node-course-documentation-error-node-wont-start/11024#11024).

You can see [at this link here](https://discord.com/channels/826816523368005654/872960725956575243/1095529242730692669) that OrangeDoug had the same issue.

I started with the nix setup from video two if that matters.
I will test again soon and report back if I still have issues.
Otherwise there is a workaround as shown in the StackExchange post.

Anyway, I love your course.
I finally feel like I have the knowledge to run a stake pool.
You have probably done the most important thing anyone can do to decentralize Cardano

**Comment by carloslodelar** [comment]
Thanks for your kind comments. I'm glad it's helping. 
And of course, let me know if you run into any other issue with the course. comments are always welcome. 

The course links to the config and topology files under https://book.world.dev.cardano.org/environments.html which is the source of truth, so perhaps there was a momentary change of the config file posted there. 

Anyways, I'm glad you were able to overcome the issue!
