### ISSUE TITLE
Missing Link to Testnet Template Config Files

### ISSUE THREAD

**Issue by Crypto2099** [carloslodelar/cardano-course#4]
In the section for running a local cluster, the link to the testnet template files is returning a 404.

> [Cardano World Testnet Templates ](https://github.com/input-output-hk/cardano-world/tree/master/nix/cardano/environments/testnet-template)is the source for our template files. These are the templates that IOG uses when we need to deploy a new testnet.

**Comment by carloslodelar** [comment]
Thank you, broken link is fixed now.
